#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************
Welcome to DigitalOcean's One-Click SKYCOIN Droplet.

To keep this droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22(SSH), 6000(node port), and 6420(node api port).

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
